### ISSUE TITLE
Question: Is this project still supported/viable?

### ISSUE THREAD

**Issue by mikeygray** [InventivetalentDev/LibreViewApi#3]
Hi @InventivetalentDev,
Stumbled on this repo and very impressed you were able to reverse engineer the Libreview API calls! Do you know if they still work? I'm curious about building something to free our data from Libreview, as Abbott (as far as I know) offer no API or SDK to do so.
Thanks very much!

**Comment by InventivetalentDev** [comment]
I haven't tried it in a while (switched to Dexcom since), but unless they did major changes to their endpoints it should still work! :)
iirc I got a bunch of the endpoints by just looking at the requests on the libreview website, so you should be able to figure out any changes

**Comment by mikeygray** [comment]
Thanks Haylee! I'll start capturing some requests from their web client and see what I can find out. Appreciate it.
