### ISSUE TITLE
Does it still work or has the authentification changed?

### ISSUE THREAD

**Issue by caffe12345** [InventivetalentDev/LibreViewApi#5]
First off, this project is amazing and with Libre 3 it will be very relevant to access LibreLinkUp to get some kind of real-time supply of information.

I ran the code with my password but unfortunately it failed with the final message being:

Logged in as undefined undefined
{"accountType":"pat","country":"DE","uiLanguage":"en-GB"}
{ message: 'invalid or expired jwt' }
401

I guess they somehow added a two-factor auth system. Would it be possible to adapt the code to maybe send out an email and let the user enter the code manually once and after that just store the token in the code?

Thanks alot for this amazing project.

**Comment by bofrese** [comment]
I have the same problem. I was attempting to rewrite it in Python, but can not get past the login. The login returns : 
```
{'data': {'authTicket': {'duration': 3600000,
                         'expires': 1642961480,
                         'token': 'eyJhb........Szlqfo'},
          'step': {'componentName': 'TwoFactorVerify',
                   'props': {'accountType': 'patient',
                             'primaryMethod': 'phone',
                             'primaryValue': '+******....',
                             'secondaryMethod': 'email',
                             'secondaryValue': '********@......com'},
                   'title': 'AccountSignUp.verifyYourIdentity',
                   'type': '2faVerify'},
          'user': {'accountType': 'pat',
                   'country': 'DK',
                   'uiLanguage': 'da-DK'}},
 'status': 4}
```
So it does indeed looks like they have introduced a two factor auth system. - And as I do not receive any SMS og email, I guess it needs a second request that triggers the 2FA. Any idea what that is?

**Comment by caffe12345** [comment]
Check out this project timoschlueter/nightscout-librelink-up - here its possible to log in and fetch current data. What is your plan? What type of app do you want to build?
